services:
  shynet:
    container_name: shynet_main
    image: ghcr.io/starkzarn/shynet:latest
    restart: unless-stopped
    ### Uncomment the following if you would like to provide updated GeoLite databases
    #volumes:
    #  - /path/to/GeoLite2-City.mmdb:/etc/GeoLite2-City.mmdb
    # - /path/to/GeoLite2-ASN.mmdb:/etc/GeoLite2-ASN.mmdb
    expose:
      - 8080
    env_file:
      # Create a file called '.env' if it doesn't already exist.
      # You can use `TEMPLATE.env` as a guide.
      - .env
    environment:
      - DB_HOST=db
    networks:
      - internal
    depends_on:
      - db
  db:
    container_name: shynet_database
    image: postgres
    restart: always
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"
    volumes:
      - shynet_db:/var/lib/postgresql/data
    networks:
      - internal
  webserver:
    container_name: shynet_webserver
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf    
    ports:
      - 8080:80
    depends_on:
      - shynet
    networks:
      - internal
  cache:
    container_name: shynet_cache
    image: redis:7-alpine
    restart: always
    networks:
      - internal

volumes:
  shynet_db:
networks:
  internal:
