# Generated by Django 5.1.5 on 2025-02-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_auto_20220624_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='fingerprint',
            field=models.TextField(blank=True, verbose_name='Fingerprint'),
        ),
    ]
